[package]
name = "cam_draw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paths = {path="../stepper_control/paths"}
clap = {version = "4.0", features = ["derive"] }
byteorder="1.4"